name: Deploy Connected Car Platform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & Push ingest-api Image
        run: |
          cd App/ingest-api
          docker buildx build --platform linux/amd64 -t ingest-api:latest .
          docker tag ingest-api:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/connected-car-ingest-api:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/connected-car-ingest-api:latest

      - name: Build & Push processor Image
        run: |
          cd App/processor
          docker buildx build --platform linux/amd64 -t processor:latest .
          docker tag processor:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/connected-car-processor:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/connected-car-processor:latest

      - name: Build & Push simulator Image
        run: |
          cd App/simulator
          docker buildx build --platform linux/amd64 -t simulator:latest .
          docker tag simulator:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/connected-car-simulator:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/connected-car-simulator:latest

      - name: Force new ECS Deployment (ingest-api)
        run: |
          aws ecs update-service \
            --cluster connected-car-cluster \
            --service connected-car-ingest-api \
            --force-new-deployment

      - name: Force new ECS Deployment (processor)
        run: |
          aws ecs update-service \
            --cluster connected-car-cluster \
            --service connected-car-processor \
            --force-new-deployment

      - name: Force new ECS Deployment (simulator)
        run: |
          aws ecs update-service \
            --cluster connected-car-cluster \
            --service connected-car-simulator \
            --force-new-deployment