name: Deploy Connected Car Platform

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug folder structure
        run: |
          pwd
          ls -la
          ls -la App
          ls -la App/ingest-api
          ls -la App/processor
          ls -la App/simulator

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build ingest-api
        run: |
          set -euxo pipefail
          cd App/ingest-api
          docker build -t ingest-api:latest .

      - name: Push ingest-api
        run: |
          set -euxo pipefail
          docker tag ingest-api:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/connected-car-ingest-api:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/connected-car-ingest-api:latest

      - name: Build processor
        run: |
          set -euxo pipefail
          cd App/processor
          docker build -t processor:latest .

      - name: Push processor
        run: |
          set -euxo pipefail
          docker tag processor:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/connected-car-processor:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/connected-car-processor:latest

      - name: Build simulator
        run: |
          set -euxo pipefail
          cd App/simulator
          docker build -t simulator:latest .

      - name: Push simulator
        run: |
          set -euxo pipefail
          docker tag simulator:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/connected-car-simulator:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/connected-car-simulator:latest

      - name: Force new ECS Deployment (ingest-api)
        run: |
          set -euxo pipefail
          aws ecs update-service \
            --cluster connected-car-cluster \
            --service connected-car-ingest-api \
            --force-new-deployment

      - name: Force new ECS Deployment (processor)
        run: |
          set -euxo pipefail
          aws ecs update-service \
            --cluster connected-car-cluster \
            --service connected-car-processor \
            --force-new-deployment

      - name: Force new ECS Deployment (simulator)
        run: |
          set -euxo pipefail
          aws ecs update-service \
            --cluster connected-car-cluster \
            --service connected-car-simulator \
            --force-new-deployment


